# Generated by Django 5.2.17 on 2026-10-01 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], verbose_name='jour')),
                ('start_time', models.TimeField(verbose_name='heure de début')),
                ('end_time', models.TimeField(verbose_name='heure de fin')),
                ('room', models.CharField(blank=True, max_length=80, verbose_name='salle')),
                ('teacher', models.CharField(blank=True, max_length=120, verbose_name='enseignant')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_entries', to='subjects.subject', verbose_name='matière')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'créneau',
                'verbose_name_plural': 'créneaux',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
    ]
