# Generated by Django 5.2.17 on 2026-10-01 20:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='titre')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('type', models.CharField(choices=[('homework', 'Devoir'), ('practical_work', 'TP'), ('project', 'Projet'), ('revision', 'Révision'), ('reading', 'Lecture'), ('exercise', 'Exercice'), ('exam', 'Examen'), ('presentation', 'Présentation'), ('other', 'Autre')], default='homework', max_length=30, verbose_name='type')),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('medium', 'Moyenne'), ('high', 'Haute'), ('urgent', 'Urgente')], default='medium', max_length=20, verbose_name='priorité')),
                ('status', models.CharField(choices=[('todo', 'À faire'), ('in_progress', 'En cours'), ('completed', 'Terminée')], default='todo', max_length=20, verbose_name='statut')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name="date d'échéance")),
                ('due_time', models.TimeField(blank=True, null=True, verbose_name="heure d'échéance")),
                ('estimated_duration', models.DecimalField(blank=True, decimal_places=2, help_text='Durée informative en heures, ex. 2.5 pour 2h30.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='durée estimée (heures)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='subjects.subject', verbose_name='matière')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tâche',
                'verbose_name_plural': 'tâches',
                'ordering': ['status', 'due_date', 'due_time', '-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='tasks_task_user_id_c0fce1_idx'), models.Index(fields=['user', 'due_date'], name='tasks_task_user_id_075050_idx'), models.Index(fields=['user', 'priority'], name='tasks_task_user_id_13ec9e_idx')],
            },
        ),
    ]
